### ISSUE TITLE
npm run build 报错

### ISSUE THREAD

**Issue by xiaobo0113** [karakal-FET/react-admin#108]
TypeScript error in D:/xiaobo/work/Github/react-admin/node_modules/jest-diff/build/diffLines.d.ts(8,13):
'=' expected.  TS1005

     6 |  */
     7 | import { Diff } from './cleanupSemantic';
  >  8 | import type { DiffOptions } from './types';
       |             ^
     9 | export declare const diffLinesUnified: (aLines: string[], bLines: string[], options?: DiffOptions | undefined) => string;
    10 | export declare const diffLinesUnified2: (aLinesDisplay: string[], bLinesDisplay: string[], aLinesCompare: string[], bLinesCompare: string[], options?: DiffOptions | undefined) => string;
    11 | export declare const diffLinesRaw: (aLines: string[], bLines: string[]) => Diff[];

**Comment by yezihaohao** [comment]
没复现出问题，你是升级了依赖包吗？

问题在jest issues里面可以找到及解决方案，可以参考一下：https://github.com/facebook/jest/issues/9703

**Comment by xiaobo0113** [comment]
我什么都没有改，你可以试着从仓库重新clone一个下来试试，看看能不能复现

**Comment by xiaobo0113** [comment]
我知道什么问题了，你在package.json中写的是`"echarts-for-react": "^2.0.15-beta.1",`注意有个`^`符号，导致了npm i的时候会去获取新版本，查看node_modules/echarts-for-react/package.json文件，发现是`"echarts-for-react@2.0.16"`，即下载了2.0.16版本的echarts-for-react，导致了和你代码中使用的api不一致。

解决办法1：去掉`^`符号，直接定死为2.0.15-beta.1版本，即在项目的package.json中写为`"echarts-for-react": "2.0.15-beta.1"即可。

解决办法2：更新业务代码，匹配2.0.16版本的echarts-for-react。
